apiVersion: v1
kind: Service
metadata:
  name: mvctest
  labels:
    name: mvctest
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31294
      name: http
  selector:
    app: mvctest